#cloud-config
users:
  - name: web
    primary_group: web
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJlJM/nKz0ReFp0a1L4JfIxFzzPrbGBR4UWKXaPACKCB kevin@Kevins-ThinkPad

package_update: true
package_upgrade: true
packages:
  - nginx
  - nmap

runcmd:
  - systemctl enable nginx
  - systemctl start nginx
